### ISSUE TITLE
Crash in MyApplication.onCreate

### ISSUE THREAD

**Issue by MoNTE48** [bugsnag/bugsnag-android#1135]
### Describe the bug
```
java.lang.AssertionError: null
    at android.util.JsonReader.peek(JsonReader.java:363)
    at android.util.JsonReader.expect(JsonReader.java:308)
    at android.util.JsonReader.beginObject(JsonReader.java:293)
    at com.bugsnag.android.DeviceId$Companion.fromReader
    at com.bugsnag.android.DeviceIdStore$loadDeviceIdInternal$1.invoke
    at com.bugsnag.android.DeviceIdStore$loadDeviceIdInternal$1.invoke
    at com.bugsnag.android.SynchronizedStreamableStore.load
    at com.bugsnag.android.DeviceIdStore.loadDeviceIdInternal
    at com.bugsnag.android.DeviceIdStore.loadDeviceId$bugsnag_android_core_release
    at com.bugsnag.android.DeviceIdStore.loadDeviceId
    at com.bugsnag.android.Client.<init>
    at com.bugsnag.android.Bugsnag.start
    at com.bugsnag.android.Bugsnag.start
    at com.***.***.MyApplication.onCreate(MyApplication.java:13)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5767)
    at android.app.ActivityThread.-wrap1
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6523)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

### Steps to reproduce
Just fin it in another crash-report service.

### Environment
* Android version: 8.1.0
* Bugsnag version: 5.6.0
* Emulator or physical device: SM-J410F

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by mattdyoung** [comment]
Hi @MoNTE48 

Thanks for reporting this. It looks like it's likely quite a rare occurrence, possibly caused by an I/O or JSON serialization error e.g. if there is insufficient space on the device.

We should be able to implement a fix protect against this scenario: https://github.com/bugsnag/bugsnag-android/pull/1137

**Comment by xander-jones** [comment]
@MoNTE48, this has been fixed in https://github.com/bugsnag/bugsnag-android/releases/tag/v5.6.2. Thanks for raising this issue with us.
