### ISSUE TITLE
Occasional background NPE in ErrorStore.write

### ISSUE THREAD

**Issue by damianw** [bugsnag/bugsnag-android#146]
Using version 3.4.0. Ignore if this has been fixed (issue with cache being cleared?).
```
java.lang.NullPointerException: Attempt to get length of null array
        at com.bugsnag.android.ErrorStore.write(ErrorStore.java:88)
        at com.bugsnag.android.Client.deliver(Client.java:626)
        at com.bugsnag.android.Client$1.run(Client.java:612)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by kattrali** [comment]
Thanks for the report, @damianw. I don't think this issue has come up before, but the code in question hasn't changed since around v3.4.0 I see how it can happen in the case that an I/O error occurs in the `listFiles` operation. I'll add a check before the length is inspected.
