### ISSUE TITLE
Possible RejectionExecutionException when calling notify()

### ISSUE THREAD

**Issue by damianw** [bugsnag/bugsnag-android#148]
Not at all frequent... we've only had a report from a single user on this issue. Not sure what the best way to queue up the error in this case would be.

```
java.util.concurrent.RejectedExecutionException: Task com.bugsnag.android.Client$1@43c840a8 rejected from java.util.concurrent.ThreadPoolExecutor@4233e1b0[Running, pool size = 3, active threads = 3, queued tasks = 128, completed tasks = 16]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1967)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:782)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1303)
        at com.bugsnag.android.Async.run(Async.java:35)
        at com.bugsnag.android.Client.notify(Client.java:720)
        at com.bugsnag.android.Client.notify(Client.java:498)
        at com.bugsnag.android.Bugsnag.notify(Bugsnag.java:360)
        at com.farmlogs.app.logging.BugReport.send(BugReport.java:147)
        at com.farmlogs.api.sync.handlers.up.SaveHandler$SaveResponseHandler.onFailure(SaveHandler.java:102)
        at com.farmlogs.api.response.ResponseHandler.postError(ResponseHandler.java:64)
        at com.farmlogs.api.response.ResponseHandler.onFailure(ResponseHandler.java:109)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:176)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
```

**Comment by kattrali** [comment]
Thanks for the report, @damianw. This is an odd one. I think we can potentially handle this by writing to disk when this happens and retrying.
