### ISSUE TITLE
java.lang.IllegalStateException: State: FLUSHED

### ISSUE THREAD

**Issue by Bencodes** [bugsnag/bugsnag-android#149]
Our application has seen a few crashes with the following stacktrace.

```text
java.lang.IllegalStateException: State: FLUSHED
        at java.nio.charset.CharsetEncoder.illegalStateException(CharsetEncoder.java:688)
        at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:366)
        at java.io.OutputStreamWriter.drainEncoder(OutputStreamWriter.java:200)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:142)
        at com.bugsnag.android.IOUtils.closeQuietly(SourceFile:19)
        at com.bugsnag.android.ErrorStore.write(SourceFile:111)
        at com.bugsnag.android.Client.deliver(SourceFile:719)
        at com.bugsnag.android.Client$1.run(SourceFile:702)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by kattrali** [comment]
Thanks for the report, @Bencodes. I'm taking a look. Can you add which version of Bugsnag you are currently running?

**Comment by fractalwrench** [comment]
I attempted to trigger this exception by writing around 100 errors to disk on multiple threads, but couldn't observe the behaviour. For further investigation, it seems from the stacktrace that the device will be in the following state:

- Running Android 6
- Using Asynchronous error notification
- Network connection failed/unavailable

**Comment by supermarin** [comment]
Looks like @Bencodes can't submit responses here, pasting for him:

> We are seeing this crash on bugsnag version 3.8.0 and it looks like the crash is only happening on Android 6.0 devices.

**Comment by kattrali** [comment]
Ah. Some content blocker or other blocks Ajax requests with "bugsnag-" in the URL. It prevents posting comments.
