### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Pirunchy75** [bugsnag/bugsnag-android#1602]
App Name: Package Manager
Package Name: com.smartpack.packagemanager
App Version: v5.9
SDK Version: 30

Crash Report

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.io.Writer.write(Writer.java:157)
	at e2.l.b(Unknown Source:5)
	at e2.b.a(:4)
	at w1.r.onClick(:27)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Steps to reproduce the issue:

**Comment by xander-jones** [comment]
Closing out for now as we've not heard back. Let us know if you've any further info on this.
