### ISSUE TITLE
ANR com.bugsnag.android.DataCollectionModule.getDeviceDataCollector

### ISSUE THREAD

**Issue by NG-Gaurav** [bugsnag/bugsnag-android#1695]
main (waiting): tid=1 systid=20998 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.bugsnag.android.DataCollectionModule.getDeviceDataCollector(DataCollectionModule.kt:71)
       at com.bugsnag.android.Client.<init>(Client.java:176)
       at com.bugsnag.android.Bugsnag.start(Bugsnag.java:64)
       at com.viewlift.hoichoi.datasource.startup.MyComponentInitializer.startBugsnag(MyComponentInitializer.kt:56)
       at com.viewlift.hoichoi.datasource.startup.MyComponentInitializer.create(MyComponentInitializer.kt:39)
       at com.viewlift.hoichoi.datasource.startup.MyComponentInitializer.create(MyComponentInitializer.kt:35)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:138)
       at androidx.startup.AppInitializer.initializeComponent(AppInitializer.java:117)
       at com.viewlift.hoichoi.HoichoiApplication.onCreate(HoichoiApplication.kt:39)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
       at android.app.ActivityThread.access$1500(ActivityThread.java:247)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by luke-belton** [comment]
Hi @NG-Gaurav - thanks for raising this, we're going to investigate and will keep you updated 👍
