### ISSUE TITLE
NullPointerException in ActivityBreadcrumbCollector when accessing Intent extras

### ISSUE THREAD

**Issue by narayan07feb** [bugsnag/bugsnag-android#2082]
### Describe the bug
A `NullPointerException` occurs in the Bugsnag library when accessing the Intent extras inside the `ActivityBreadcrumbCollector.setActivityIntentMetadata` method. The issue arises when the Intent passed to the Activity does not contain extras, leading to a crash while trying to retrieve them.

### Steps to reproduce
Unable to reproduce as this issue is only occurring in the production build. The crash seems to happen in certain user environments, but we haven't been able to replicate it during testing.

### Environment
* Android version: 6.0.0 to 8.0.0 as per report 
* Bugsnag version: 6.7.0
* Emulator or physical device: Physical device

<details><summary>
</summary>

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Parcel.dataSize()' on a null object reference
    at android.os.BaseBundle.<init>(BaseBundle.java:126)
    at android.os.Bundle.<init>(Bundle.java:102)
    at android.content.Intent.getExtras(Intent.java:5694)
    at com.bugsnag.android.ActivityBreadcrumbCollector.setActivityIntentMetadata(ActivityBreadcrumbCollector:82)
    at com.bugsnag.android.ActivityBreadcrumbCollector.onActivityCreated(ActivityBreadcrumbCollector:22)
```
</details>

**Comment by clr182** [comment]
Hi @narayan07feb 

Thank you for reaching out and raising this issue. We are looking to implement a fix ASAP and will be sure to update this thread once the release is Live.
