### ISSUE TITLE
ConcurrentModificationException while call Bugsnag.notify()

### ISSUE THREAD

**Issue by Tougee** [bugsnag/bugsnag-android#281]
```Java
java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
        at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
        at com.bugsnag.android.Client.runBeforeNotifyTasks(Client.java:1009)
        at com.bugsnag.android.Client.notify(Client.java:924)
        at com.bugsnag.android.Client.notify(Client.java:899)
        at com.bugsnag.android.Client.notify(Client.java:656)
        at com.bugsnag.android.Bugsnag.notify(Bugsnag.java:346)
```

**Comment by fractalwrench** [comment]
This should be resolved in 4.3.2 by #266 - please let us know if that's not the case, and I'll reopen this ticket.

**Comment by Tougee** [comment]
The version of my is 4.3.1, I'll check this in 4.3.2, thank your for apply

**Comment by panser** [comment]
see the same error in `bugsnag-spring`
