### ISSUE TITLE
Bugsnag blocks the main thread

### ISSUE THREAD

**Issue by ghazel** [bugsnag/bugsnag-android#287]
### Expected behavior
Bugsnag never blocks the main thread

### Observed behavior
Bugsnag blocks the main thread

### Steps to reproduce
Use Bugsnag on a very slow, basically inoperable network (but *not* disconnected)

### Version
4.3.0 (because the latest `bugsnag-android-ndk` is pinned to 4.3.0)

### Additional information

Main thread:

```java
"main@5024" prio=5 tid=0x2 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for Bugsnag Delivery Thread@5320 to release lock on <0x1832> (a com.bugsnag.android.SessionStore)
	  at com.bugsnag.android.SessionTracker.startNewSession(SessionTracker.java:71)
	  at com.bugsnag.android.SessionTracker.updateForegroundTracker(SessionTracker.java:253)
	  at com.bugsnag.android.SessionTracker.onActivityStarted(SessionTracker.java:181)
	  at android.app.Application.dispatchActivityStarted(Application.java:207)
	  at android.app.Activity.onStart(Activity.java:1245)
	  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:589)
	  at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
	  at android.app.Activity.performStart(Activity.java:7029)
	  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	  at android.app.ActivityThread.-wrap11(ActivityThread.java:-1)
	  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	  at android.os.Handler.dispatchMessage(Handler.java:106)
	  at android.os.Looper.loop(Looper.java:164)
	  at android.app.ActivityThread.main(ActivityThread.java:6494)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

"Bugsnag Delivery Thread@5320" prio=5 tid=0x397 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.SocketInputStream.socketRead0(SocketInputStream.java:-1)
	  at java.net.SocketInputStream.socketRead(SocketInputStream.java:114)
	  at java.net.SocketInputStream.read(SocketInputStream.java:170)
	  at java.net.SocketInputStream.read(SocketInputStream.java:139)
	  at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
	  at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	  at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	  at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	  at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	  at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	  at com.android.okhttp.internal.io.RealConnection.createTunnel(RealConnection.java:270)
	  at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:172)
	  at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	  at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	  at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	  at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	  at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
	  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:-1)
	  at com.bugsnag.android.DefaultHttpClient.makeRequest(DefaultHttpClient.java:67)
	  at com.bugsnag.android.DefaultHttpClient.postSessionTrackingPayload(DefaultHttpClient.java:38)
	  at com.bugsnag.android.SessionTracker.flushStoredSessions(SessionTracker.java:154)
	  - locked <0x1832> (a com.bugsnag.android.SessionStore)
	  at com.bugsnag.android.Client$2.run(Client.java:229)
	  at android.os.Handler.handleCallback(Handler.java:790)
	  at android.os.Handler.dispatchMessage(Handler.java:99)
	  at android.os.Looper.loop(Looper.java:164)
	  at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by fractalwrench** [comment]
We're sorry you're experiencing this @ghazel - this issue was resolved in [v4.3.1](https://github.com/bugsnag/bugsnag-android/releases/tag/v4.3.1), and can occur in v4.3.0 on slow network connections.

**Comment by ghazel** [comment]
Could you upgrade `bugsnag-android-ndk` so that I can use the fixed version?

**Comment by fractalwrench** [comment]
Sorry about that, I missed the part about the NDK in the original report. We'll work on a release now.

**Comment by kattrali** [comment]
Currently waiting for the artifacts for bugsnag-android-ndk v1.1.3 to propagate to bintray and maven central.
