### ISSUE TITLE
OOM bugsnag write

### ISSUE THREAD

**Issue by crossle** [bugsnag/bugsnag-android#288]
This log come from bugsnag, OOM when write log
### Expected behavior
java.lang.OutOfMemoryError: Failed to allocate a 508 byte allocation with 16777216 free bytes and 16MB until OOM; failed due to fragmentation (required continguous free 32768 bytes for a new buffer where largest contiguous free 28672 bytes)
        at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
        at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:163)
        at java.lang.StringBuilder.append(StringBuilder.java:311)
        at java.lang.StringBuilder.append(StringBuilder.java:310)
        at java.util.Formatter.outputCharSequence(Formatter.java:1094)
        at java.util.Formatter.doFormat(Formatter.java:1066)
        at java.util.Formatter.format(Formatter.java:1042)
        at java.util.Formatter.format(Formatter.java:1011)
        at java.lang.String.format(String.java:1554)
        at java.lang.String.format(String.java:1528)
        at com.bugsnag.android.FileStore.write(FileStore.java:60)
        at com.bugsnag.android.Client.notify(Client.java:910)
        at com.bugsnag.android.Client.notify(Client.java:846)
        at com.bugsnag.android.Client.notify(Client.java:705)
        at com.bugsnag.android.Bugsnag.notify(Bugsnag.java:372)

### Version
4.3.2

**Comment by fractalwrench** [comment]
@crossle thanks for the report. It looks like there isn't enough space to write an error report to disc, which is the cause of the crash. Is it possible that `notify` is being called in an infinite loop within your application?

This [particular stacktrace](https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/Client.java#L910) should only be generated if many errors are notified around the same time, which could also explain the lack of disc space.

I'll mark this as a bug as I think our SDK should catch this exception and log a warning, rather than crashing outright.

**Comment by crossle** [comment]
OK, thanks, i notify some bug like 
            Bugsnag.beforeNotify {
                it.addToTab("Decrypt", "conversation", data.conversationId)
                true
            }
            Bugsnag.notify(e)
is it right?

**Comment by fractalwrench** [comment]
Yes, this is correct if you wanted to notify of a non-fatal error.

**Comment by fractalwrench** [comment]
I've looked at this again in more detail, and `FileStore` actually already catches any exception and logs a warning. The OOM Error occurred due to there not being enough memory to perform string formatting at the following line:

```
Logger.warn(String.format("Discarding oldest error as stored "
                    + "error limit reached (%s)", files[0].getPath()));
```

We'd recommend trying out [LeakCanary](https://github.com/square/leakcanary/) in your app, as generally OOM errors are caused by memory leaks elsewhere in an application, or by loading very large Bitmaps. If you're able to consistently reproduce the issue then please comment and I'll reopen this.

**Comment by Tougee** [comment]
After calling <code>notify</code> many times(as much as infinite loop), and see logs like these

```java
W/Bugsnag: Exceeded max queue count, saving to disk to send later

java.io.FileNotFoundException: /data/user/0/package/cache/bugsnag-errors/1524118423353_6cff8d25-bf51-4a1c-845f-8afae22b3879.json (Too many open files)
at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
        at java.io.FileWriter.<init>(FileWriter.java:63)
        at com.bugsnag.android.FileStore.write(FileStore.java:72)
        at com.bugsnag.android.Client.deliver(Client.java:1248)
        at com.bugsnag.android.Client$2.run(Client.java:907)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
Did <code>notify</code> open lots of files?

**Comment by fractalwrench** [comment]
@Tougee `notify` will attempt to send an error report asynchronously. If it is called in an infinite loop then the Thread Pool will start rejecting execution, and write a report to disc so that it can send it later. In this scenario the system has run out of resources, so can't open any other files.

The fix would be to avoid causing `notify` in an infinite loop if at all possible - previous error reports should help track down the root cause. Hope that helps.
