### ISSUE TITLE
Error receiving broadcast intent

### ISSUE THREAD

**Issue by jrodbx** [bugsnag/bugsnag-android#363]
### Expected behavior
No crash.

### Observed behavior
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 bqHint=4 (has extras) } in com.bugsnag.android.Client$ConnectivityChangeReceiver@3906bed
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1003)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7225)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.NetworkInfo android.net.ConnectivityManager.getActiveNetworkInfo()' on a null object reference
        at com.bugsnag.android.Client$ConnectivityChangeReceiver.onReceive(Client.java:225)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:993)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7225)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

### Version
com.bugsnag:bugsnag-android:4.5.0

**Comment by fractalwrench** [comment]
Thanks for the detailed report (and PR) @jrodbx. It seems that `context.getSystemService` can return a nullable - we'll update the other cases within the SDK where this could be an issue.
