### ISSUE TITLE
Problem with `Configuration#beforeSend`

### ISSUE THREAD

**Issue by anastasia-zaitsewa** [bugsnag/bugsnag-android#417]
### Expected behavior
Non-native crashes should be delivered too.

### Observed behavior
Only native crashes are delivered.

### Steps to reproduce
1) Use `configuration#beforeSend` to add custom tabs.
Here is the code snippet:
```koltin
 val configuration = Configuration(BUGSNAG_API_KEY)

configuration.beforeSend {
            it.error?.addToTab(
                "Info",
                "Installer Source",
                installationInfo.getInstallerPackageName() // string which is never null
            )

            return@beforeSend true
        }
Bugsnag.init(context, configuration)
```
2) Observe that non-native crashes aren't being delivered anymore:
Here is my usual report when testing Bugsnag. It contains both native and non-native errors:
<img width="984" alt="screenshot 2019-01-17 at 14 30 57" src="https://user-images.githubusercontent.com/3982686/51322013-93c93680-1a64-11e9-97ba-647242eedb10.png">

And here how it looks like whenever I use `beforeSend` (receiving only native reports):
<img width="918" alt="screenshot 2019-01-17 at 14 32 30" src="https://user-images.githubusercontent.com/3982686/51322108-d2f78780-1a64-11e9-8735-7daa70a79da0.png">

3) And here is the console output which I am getting whenever I use `beforeSend` and reproting native crash:
```
2019-01-17 12:09:13.347 32204-32204/package.name W/BugsnagNDK: Initialization complete! 
2019-01-17 12:09:14.282 32204-32285/package.name I/Bugsnag: Completed session tracking request 
2019-01-17 12:09:15.232 32290-32290/package.name W/BugsnagNDK: Initialization complete! 
2019-01-17 12:09:39.078 32204-32204/package.name I/Bugsnag: Saved unsent payload to disk (/data/user/0/package.name/cache/bugsnag-errors/1547723379052_85ef4a87-8071-4d52-8f79-5c3e30c0d6f3.json)  
2019-01-17 12:09:39.080 32204-32267/package.name I/Bugsnag: Sending 1 saved error(s) to Bugsnag 
2019-01-17 12:09:39.093 32204-32267/package.name W/Bugsnag: Problem sending unsent error from disk     
java.lang.IllegalStateException: Expected END_ARRAY but was BEGIN_OBJECT         
at android.util.JsonReader.expect(JsonReader.java:310)         
at android.util.JsonReader.endArray(JsonReader.java:285)         
at com.bugsnag.android.ErrorReader.readExceptions(ErrorReader.java:197)         
at com.bugsnag.android.ErrorReader.readError(ErrorReader.java:61)         
at com.bugsnag.android.ErrorStore.flushErrorReport(ErrorStore.java:138)         
at com.bugsnag.android.ErrorStore.flushReports(ErrorStore.java:126)         
at com.bugsnag.android.ErrorStore$3.run(ErrorStore.java:111)         
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)         
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)         
at java.lang.Thread.run(Thread.java:764)
```
### Version
com.bugsnag:bugsnag-android-ndk:4.10.0

### Additional information
My end goal in here is to attach custom information in form of a tab to each report.
So far I found two slightly different ways to do that for normal (not native) errors:

1) Use `configuration.metaData.addToTab`
```kotlin
configuration.metaData.addToTab(
            "Info",
            "Installer Source",
             installationInfo.getInstallerPackageName() // string which is never null
        )
```

2) Use `beforeNotify`
```kotlin
Bugsnag.beforeNotify {
            it.addToTab(
            "Info",
            "Installer Source",
             installationInfo.getInstallerPackageName() // string which is never null
            )

            return@beforeNotify true
        }
```

And both of them work for non-native crashes and the info shows up in console correctly (custom tab is "INFO"):
<img width="463" alt="screenshot 2019-01-17 at 14 27 39" src="https://user-images.githubusercontent.com/3982686/51321834-1d2c3900-1a64-11e9-99e4-33cc5239b7dd.png">

However, it doesn't work for native crashes and there is a mention for documentation that `beforeSend` should be used for that.
If I use just `beforeSend` on its own or in combination with `beforeNotify` or `configuration.metaData.addToTab` non-native crashes aren't reported anymore and I see native reports only.

Other observations:

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by fractalwrench** [comment]
Thanks for the detailed report @anastasia-zaitsewa - I've reproduced the behaviour and it appears that this is a serialisation bug within the SDK. This behaviour occurs when the following conditions are true:

- A `Throwable` with an additional `Throwable` as a cause is thrown
- The report is cached on disk due to delivery failure
- A beforeSend callback is specified.

We're working on a fix to resolve this. Until a fix is released, as a workaround we'd recommend commenting out any `beforeSend` callbacks, as this should allow non-native errors to be delivered.
