### ISSUE TITLE
ConcurrentModificationException in Breadcrumbs

### ISSUE THREAD

**Issue by rsajob** [bugsnag/bugsnag-android#72]
I received java.util.ConcurrentModificationException if first call Bugsnag.notify() and then call Bugsnag.leaveBreadcrumb() in UI Thread.

StackTrace:
```
Problem sending error to Bugsnag
    java.util.ConcurrentModificationException
            at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
            at com.bugsnag.android.Breadcrumbs.toStream(Breadcrumbs.java:27)
            at com.bugsnag.android.JsonStream.value(JsonStream.java:37)
            at com.bugsnag.android.Error.toStream(Error.java:97)
            at com.bugsnag.android.JsonStream.value(JsonStream.java:37)
            at com.bugsnag.android.Notification.toStream(Notification.java:40)
            at com.bugsnag.android.HttpClient.post(HttpClient.java:38)
            at com.bugsnag.android.Notification.deliver(Notification.java:64)
            at com.bugsnag.android.Client.deliver(Client.java:619)
            at com.bugsnag.android.Client.access$000(Client.java:19)
            at com.bugsnag.android.Client$1.run(Client.java:611)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by kattrali** [comment]
Fixed by #98.
