### ISSUE TITLE
ANRs incorrectly grouped together

### ISSUE THREAD

**Issue by pyricau** [bugsnag/bugsnag-android#915]
We recently enabled ANR detection, usnig Bugsnag 5.

Here are two ANR stacktraces that Bugsnag grouped in the same group:

```
ANR:  Broadcast of Intent { act=android.intent.action.SCREEN_OFF flg=0x50000010 (has extras) }
        at dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
        at java.lang.Thread.getStackTrace(Thread.java:580)
        at com.bugsnag.android.AnrPlugin.notifyAnrDetected(AnrPlugin.kt:52)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:168)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:162)
        at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:155)
        at android.view.Display.updateDisplayInfoLocked(Display.java:947)
        at android.view.Display.updateDisplayInfoLocked(Display.java:933)
        at android.view.Display.getRealSize(Display.java:867)
        at android.view.ThreadedRenderer.setLightCenter(ThreadedRenderer.java:272)
        at android.view.ThreadedRenderer.setup(ThreadedRenderer.java:265)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2276)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1438)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7416)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
        at android.view.Choreographer.doCallbacks(Choreographer.java:695)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7230)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

```
ANR:  Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 8.  Wait queue head age: 11688.4ms.)
        at dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
        at java.lang.Thread.getStackTrace(Thread.java:580)
        at com.bugsnag.android.AnrPlugin.notifyAnrDetected(AnrPlugin.kt:52)
        at java.lang.Object.wait(Object.java:-2)
        at java.lang.Thread.parkFor(Thread.java:1220)
        at sun.misc.Unsafe.park(Unsafe.java:299)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:973)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:202)
        at android.app.SharedPreferencesImpl$EditorImpl$1.run(SharedPreferencesImpl.java:363)
        at android.app.QueuedWork.waitToFinish(QueuedWork.java:88)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2900)
        at android.app.ActivityThread.access$2100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

As you can see, these two ANRs seem very different, so it's not clear why they're grouped together except maybe that the top of the stacktrace is similar but that part is actually added by Bugsnag Android and shouldn't be included in how bugsnag handles groupnig.

**Comment by pyricau** [comment]
Looking further it seems like all ANRs are grouped together. Is that intentional? It makes it impossible to prioritize some ANRs over others.

**Comment by xander-jones** [comment]
Hey @pyricau, can you please drop us a message at support@bugsnag.com with links to the events in your dashboard? We're able to see a few separate ANR's at the moment.

**Comment by peterdk** [comment]
Just mentioning that this is the reason we stopped using ANR detection. I had like 200 ANR's in one error grouped, while they were like 20 different ones.

**Comment by steve-nester-uk** [comment]
@pyricau thanks for sending the examples through.  As discussed in the email, it looks like this was a function of how the in-project function was used.. mentioning this here in case anyone else sees the same issue:

The ANR's were grouping based on the top in-project stackframe.  As all the stackframes were not in-project, we grouped all the ANRs together.
In-project frames are deduced using [projectPackages](https://docs.bugsnag.com/platforms/android/configuration-options/#projectpackages) configuration option. This option contains an array of packages which are used to work out if frames are in project or not. This defaults to the package from which Bugsnag was started, but can be overridden on initialization of Bugsnag as follows:

```
val config = Configuration.load(this)
config.projectPackages = setOf("com.company.package1", "com.company.package2")
Bugsnag.start(this, config)
```
